package view;

import model.Credencial;
import data.CredencialDAO;
import utils.*;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;

public class JFLogin extends javax.swing.JFrame {

    Credencial credencial;
    CredencialDAO credencialDAO;
    Paineis paineis;

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();

        try {
            credencial = new Credencial();
            credencialDAO = new CredencialDAO();
            paineis = new Paineis();
        } catch (Exception e) {
            System.err.println("Erro ao abrir instância de " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpTitulo = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jpCentral = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jlSenha = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jcbMostrarSenha = new javax.swing.JCheckBox();
        jpLogin = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 440));
        setResizable(false);

        jpTitulo.setBackground(new java.awt.Color(0, 146, 255));
        jpTitulo.setName(""); // NOI18N
        jpTitulo.setPreferredSize(new java.awt.Dimension(360, 60));
        jpTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jlTitulo.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Bem-vindo!");
        jpTitulo.add(jlTitulo);

        getContentPane().add(jpTitulo, java.awt.BorderLayout.NORTH);
        jpTitulo.getAccessibleContext().setAccessibleName("");

        jpCentral.setBackground(new java.awt.Color(255, 109, 0));
        jpCentral.setMaximumSize(new java.awt.Dimension(360, 360));
        jpCentral.setMinimumSize(new java.awt.Dimension(360, 360));
        jpCentral.setPreferredSize(new java.awt.Dimension(360, 360));
        java.awt.GridBagLayout jpCentralLayout = new java.awt.GridBagLayout();
        jpCentralLayout.columnWidths = new int[] {120};
        jpCentralLayout.rowHeights = new int[] {30};
        jpCentral.setLayout(jpCentralLayout);

        jlUsuario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlUsuario.setText("Usuário:");
        jlUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 20);
        jpCentral.add(jlUsuario, gridBagConstraints);

        jtfUsuario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 40);
        jpCentral.add(jtfUsuario, gridBagConstraints);

        jlSenha.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlSenha.setText("Senha:");
        jlSenha.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 20);
        jpCentral.add(jlSenha, gridBagConstraints);

        jpfSenha.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jpfSenha.setNextFocusableComponent(jpLogin);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 40);
        jpCentral.add(jpfSenha, gridBagConstraints);

        jcbMostrarSenha.setBackground(new java.awt.Color(255, 109, 0));
        jcbMostrarSenha.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jcbMostrarSenha.setText("Mostrar senha");
        jcbMostrarSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jcbMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMostrarSenhaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jpCentral.add(jcbMostrarSenha, gridBagConstraints);

        getContentPane().add(jpCentral, java.awt.BorderLayout.CENTER);

        jpLogin.setBackground(new java.awt.Color(0, 146, 255));
        jpLogin.setPreferredSize(new java.awt.Dimension(360, 80));
        jpLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpLoginFocusLost(evt);
            }
        });
        jpLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLoginMouseExited(evt);
            }
        });
        jpLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpLoginKeyPressed(evt);
            }
        });
        jpLogin.setLayout(new java.awt.GridLayout(1, 0));

        jlLogin.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jlLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogin.setText("Acessar");
        jpLogin.add(jlLogin);

        getContentPane().add(jpLogin, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(376, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLoginMouseClicked
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (credencialDAO.verificarCredenciais(credencial)) {
                        //JOptionPane.showMessageDialog(this, "Sucesso!", "Login", JOptionPane.INFORMATION_MESSAGE);
                        //Inicializar o JFPrincipal.
                        JFPrincipal loggedIn = new JFPrincipal();
                        loggedIn.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Usuário e/ou senha inválidos.", "Login", JOptionPane.ERROR_MESSAGE);
                        limparCampos();
                        jtfUsuario.requestFocus();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Login", JOptionPane.ERROR_MESSAGE);
            limparCampos();
            jtfUsuario.requestFocus();
        }
    }//GEN-LAST:event_jpLoginMouseClicked

    private void jpLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpLoginKeyPressed
        //Se a tecla for "Enter", cujo código é 10. Como visualizar isso?
        //System.out.println("KeyCode: " + evt.getKeyCode());
        if (evt.getKeyCode() == 10) {
            try {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (credencialDAO.verificarCredenciais(credencial)) {
                            //JOptionPane.showMessageDialog(this, "Sucesso!", "Login", JOptionPane.INFORMATION_MESSAGE);
                            //Inicializar o JFPrincipal.
                            JFPrincipal loggedIn = new JFPrincipal();
                            loggedIn.setVisible(true);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Usuário e/ou senha inválidos.", "Login", JOptionPane.ERROR_MESSAGE);
                            limparCampos();
                            jtfUsuario.requestFocus();
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Login", JOptionPane.ERROR_MESSAGE);
                limparCampos();
                jtfUsuario.requestFocus();
            }
        }
    }//GEN-LAST:event_jpLoginKeyPressed

    private void jpLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpLoginFocusGained
        paineis.componentSetLineBorderColor(jpLogin);
    }//GEN-LAST:event_jpLoginFocusGained

    private void jpLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpLoginFocusLost
        paineis.componentSetEmptyBorder(jpLogin);
    }//GEN-LAST:event_jpLoginFocusLost

    private void jpLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLoginMouseEntered
        paineis.componentSetLineBorderColor(jpLogin);
    }//GEN-LAST:event_jpLoginMouseEntered

    private void jpLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLoginMouseExited
        paineis.componentSetEmptyBorder(jpLogin);
    }//GEN-LAST:event_jpLoginMouseExited

    private void jcbMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMostrarSenhaActionPerformed
        if (jcbMostrarSenha.isSelected()) {
            jpfSenha.setEchoChar((char) 0);
        } else {
            jpfSenha.setEchoChar('•');
        }
    }//GEN-LAST:event_jcbMostrarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.install();

        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jcbMostrarSenha;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    public void limparCampos() {
        jtfUsuario.setText("");
        jpfSenha.setText("");
    }

    public boolean validarCampos() throws Exception {
        if (jtfUsuario.getText().trim().length() < 1 || jtfUsuario.getText().trim().length() > 40) {
            throw new Exception("Usuário e/ou senha inválidos.");
        }
        if (jpfSenha.getText().trim().length() < 1 || jpfSenha.getText().trim().length() > 40) {
            throw new Exception("Usuário e/ou senha inválidos.");
        }

        return true;
    }

    public boolean preencherObjeto() {
        credencial.setUsuario(jtfUsuario.getText());
        credencial.setSenha(jpfSenha.getText());

        return true;
    }
}
